SET IDENTITY_INSERT [dbo].[WEEKDAYS] ON
INSERT INTO [dbo].[WEEKDAYS] ([ID_WEEKDAY], [NAME_WEEKDAY]) VALUES (1, N'Понедельник')
INSERT INTO [dbo].[WEEKDAYS] ([ID_WEEKDAY], [NAME_WEEKDAY]) VALUES (2, N'Вторник')
INSERT INTO [dbo].[WEEKDAYS] ([ID_WEEKDAY], [NAME_WEEKDAY]) VALUES (3, N'Среда')
INSERT INTO [dbo].[WEEKDAYS] ([ID_WEEKDAY], [NAME_WEEKDAY]) VALUES (4, N'Четверг')
INSERT INTO [dbo].[WEEKDAYS] ([ID_WEEKDAY], [NAME_WEEKDAY]) VALUES (5, N'Пятница')
INSERT INTO [dbo].[WEEKDAYS] ([ID_WEEKDAY], [NAME_WEEKDAY]) VALUES (6, N'Суббота')
INSERT INTO [dbo].[WEEKDAYS] ([ID_WEEKDAY], [NAME_WEEKDAY]) VALUES (7, N'Воскресенье')
SET IDENTITY_INSERT [dbo].[WEEKDAYS] OFF
