SET IDENTITY_INSERT [dbo].[DEPARTMENTS] ON
INSERT INTO [dbo].[DEPARTMENTS] ([ID_DEPARTMENT], [ID_ORGANIZATION], [NAME_DEPARTMENT]) VALUES (1, 1, N'Кредитный отдел')
INSERT INTO [dbo].[DEPARTMENTS] ([ID_DEPARTMENT], [ID_ORGANIZATION], [NAME_DEPARTMENT]) VALUES (2, 2, N'Запрещающий отдел')
INSERT INTO [dbo].[DEPARTMENTS] ([ID_DEPARTMENT], [ID_ORGANIZATION], [NAME_DEPARTMENT]) VALUES (3, 3, N'Пищевой отдел')
INSERT INTO [dbo].[DEPARTMENTS] ([ID_DEPARTMENT], [ID_ORGANIZATION], [NAME_DEPARTMENT]) VALUES (4, 4, N'Свиной отдел')
INSERT INTO [dbo].[DEPARTMENTS] ([ID_DEPARTMENT], [ID_ORGANIZATION], [NAME_DEPARTMENT]) VALUES (5, 5, N'Религиозный отдел')
INSERT INTO [dbo].[DEPARTMENTS] ([ID_DEPARTMENT], [ID_ORGANIZATION], [NAME_DEPARTMENT]) VALUES (6, 6, N'Отверточный отдел')
INSERT INTO [dbo].[DEPARTMENTS] ([ID_DEPARTMENT], [ID_ORGANIZATION], [NAME_DEPARTMENT]) VALUES (7, 1, N'Вымогательный отдел')
INSERT INTO [dbo].[DEPARTMENTS] ([ID_DEPARTMENT], [ID_ORGANIZATION], [NAME_DEPARTMENT]) VALUES (8, 2, N'Разрешающий отдел')
INSERT INTO [dbo].[DEPARTMENTS] ([ID_DEPARTMENT], [ID_ORGANIZATION], [NAME_DEPARTMENT]) VALUES (9, 3, N'Опасный отдел')
SET IDENTITY_INSERT [dbo].[DEPARTMENTS] OFF
