SET IDENTITY_INSERT [dbo].[POSITIONS] ON
INSERT INTO [dbo].[POSITIONS] ([ID_POSITION], [ID_DEPARTMENT], [NAME_POSITION]) VALUES (1, 1, N'Коллектор')
INSERT INTO [dbo].[POSITIONS] ([ID_POSITION], [ID_DEPARTMENT], [NAME_POSITION]) VALUES (2, 2, N'Песик')
INSERT INTO [dbo].[POSITIONS] ([ID_POSITION], [ID_DEPARTMENT], [NAME_POSITION]) VALUES (3, 3, N'Хомячок')
INSERT INTO [dbo].[POSITIONS] ([ID_POSITION], [ID_DEPARTMENT], [NAME_POSITION]) VALUES (4, 4, N'Мясник')
INSERT INTO [dbo].[POSITIONS] ([ID_POSITION], [ID_DEPARTMENT], [NAME_POSITION]) VALUES (5, 5, N'Священник')
INSERT INTO [dbo].[POSITIONS] ([ID_POSITION], [ID_DEPARTMENT], [NAME_POSITION]) VALUES (6, 6, N'Фортачник')
INSERT INTO [dbo].[POSITIONS] ([ID_POSITION], [ID_DEPARTMENT], [NAME_POSITION]) VALUES (7, 1, N'Списатель')
INSERT INTO [dbo].[POSITIONS] ([ID_POSITION], [ID_DEPARTMENT], [NAME_POSITION]) VALUES (8, 2, N'Шпион')
INSERT INTO [dbo].[POSITIONS] ([ID_POSITION], [ID_DEPARTMENT], [NAME_POSITION]) VALUES (9, 3, N'Не хомячок')
INSERT INTO [dbo].[POSITIONS] ([ID_POSITION], [ID_DEPARTMENT], [NAME_POSITION]) VALUES (10, 4, N'Барыга')
SET IDENTITY_INSERT [dbo].[POSITIONS] OFF
