SET IDENTITY_INSERT [dbo].[EMPLOYEE_STATUSES] ON
INSERT INTO [dbo].[EMPLOYEE_STATUSES] ([ID_EMPLOYEE_STATUS], [NAME_EMPLOYEE_STATUS]) VALUES (1, N'активный')
INSERT INTO [dbo].[EMPLOYEE_STATUSES] ([ID_EMPLOYEE_STATUS], [NAME_EMPLOYEE_STATUS]) VALUES (2, N'уволен')
INSERT INTO [dbo].[EMPLOYEE_STATUSES] ([ID_EMPLOYEE_STATUS], [NAME_EMPLOYEE_STATUS]) VALUES (3, N'в архиве')
INSERT INTO [dbo].[EMPLOYEE_STATUSES] ([ID_EMPLOYEE_STATUS], [NAME_EMPLOYEE_STATUS]) VALUES (4, N'истёк срок действия,')
INSERT INTO [dbo].[EMPLOYEE_STATUSES] ([ID_EMPLOYEE_STATUS], [NAME_EMPLOYEE_STATUS]) VALUES (5, N'больничный')
INSERT INTO [dbo].[EMPLOYEE_STATUSES] ([ID_EMPLOYEE_STATUS], [NAME_EMPLOYEE_STATUS]) VALUES (6, N'отпуск')
SET IDENTITY_INSERT [dbo].[EMPLOYEE_STATUSES] OFF
