SET IDENTITY_INSERT [dbo].[TYPES_ORGANIZATION] ON
INSERT INTO [dbo].[TYPES_ORGANIZATION] ([ID_TYPE_ORGANIZATION], [NAME_TYPE_ORGANIZATION]) VALUES (1, N'ООО')
INSERT INTO [dbo].[TYPES_ORGANIZATION] ([ID_TYPE_ORGANIZATION], [NAME_TYPE_ORGANIZATION]) VALUES (2, N'АО')
INSERT INTO [dbo].[TYPES_ORGANIZATION] ([ID_TYPE_ORGANIZATION], [NAME_TYPE_ORGANIZATION]) VALUES (3, N'ИП')
SET IDENTITY_INSERT [dbo].[TYPES_ORGANIZATION] OFF
