SET IDENTITY_INSERT [dbo].[ACCOUNT_STATUSES] ON
INSERT INTO [dbo].[ACCOUNT_STATUSES] ([ID_ACCOUNT_STATUS], [NAME_ACCOUNT_STATUS]) VALUES (1, N'активная')
INSERT INTO [dbo].[ACCOUNT_STATUSES] ([ID_ACCOUNT_STATUS], [NAME_ACCOUNT_STATUS]) VALUES (2, N'неактивная')
INSERT INTO [dbo].[ACCOUNT_STATUSES] ([ID_ACCOUNT_STATUS], [NAME_ACCOUNT_STATUS]) VALUES (3, N'заблокирована')
INSERT INTO [dbo].[ACCOUNT_STATUSES] ([ID_ACCOUNT_STATUS], [NAME_ACCOUNT_STATUS]) VALUES (4, N'в архиве')
SET IDENTITY_INSERT [dbo].[ACCOUNT_STATUSES] OFF
