SET IDENTITY_INSERT [dbo].[ORGANIZATIONS] ON
INSERT INTO [dbo].[ORGANIZATIONS] ([ID_ORGANIZATION], [ID_TYPE_ORGANIZATION], [NAME_ORGANIZATION]) VALUES (1, 1, N'Долг')
INSERT INTO [dbo].[ORGANIZATIONS] ([ID_ORGANIZATION], [ID_TYPE_ORGANIZATION], [NAME_ORGANIZATION]) VALUES (2, 2, N'Мизулина')
INSERT INTO [dbo].[ORGANIZATIONS] ([ID_ORGANIZATION], [ID_TYPE_ORGANIZATION], [NAME_ORGANIZATION]) VALUES (3, 3, N'Голодные Хомячки')
INSERT INTO [dbo].[ORGANIZATIONS] ([ID_ORGANIZATION], [ID_TYPE_ORGANIZATION], [NAME_ORGANIZATION]) VALUES (4, 1, N'Медальоны')
INSERT INTO [dbo].[ORGANIZATIONS] ([ID_ORGANIZATION], [ID_TYPE_ORGANIZATION], [NAME_ORGANIZATION]) VALUES (5, 2, N'Иссус')
INSERT INTO [dbo].[ORGANIZATIONS] ([ID_ORGANIZATION], [ID_TYPE_ORGANIZATION], [NAME_ORGANIZATION]) VALUES (6, 3, N'Отвертка')
SET IDENTITY_INSERT [dbo].[ORGANIZATIONS] OFF
