CREATE TABLE ACCOUNT_STATUSES
(
    ID_ACCOUNT_STATUS INT IDENTITY(1,1) NOT NULL,
    NAME_ACCOUNT_STATUS VARCHAR(50) NULL DEFAULT 'NEW_ACCOUNT_STATUS',

    PRIMARY KEY CLUSTERED (ID_ACCOUNT_STATUS ASC)
)