CREATE TABLE ACCOUNTS
(
    ID_ACCOUNT INT IDENTITY(1,1) NOT NULL,
    ID_EMPLOYEE INT NULL,
    ID_SCHEDULE INT NULL,
    ID_ACCOUNT_STATUS INT NULL,
    ID_ROLE INT NULL,
    LOGIN_ACCOUNT VARCHAR(50) NULL DEFAULT 'NEW_LOGIN',
    PASSWORD_ACCOUNT VARCHAR(50) NULL DEFAULT 'NEW_PASSWORD',
    PERIOD_VALIDITY_FROM DATE NULL,
    PERIOD_VALIDITY_BY DATE NULL,
    LAST_LOGIN DATE NULL,
    LAST_PASSWORD_CHANGE DATE NULL,

    PRIMARY KEY CLUSTERED (ID_ACCOUNT ASC),
    CONSTRAINT FK_EMPLOYEES_ACCOUNTS FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEES (ID_EMPLOYEE),
    CONSTRAINT FK_SCHEDULES_ACCOUNTS FOREIGN KEY (ID_SCHEDULE) REFERENCES SCHEDULES (ID_SCHEDULE),
    CONSTRAINT FK_ACCOUNT_STATUSES_ACCOUNTS FOREIGN KEY (ID_ACCOUNT_STATUS) REFERENCES ACCOUNT_STATUSES (ID_ACCOUNT_STATUS),
    CONSTRAINT FK_ROLES_ACCOUNTS FOREIGN KEY (ID_ROLE) REFERENCES ROLES (ID_ROLE)
)