CREATE TABLE ACCOUNTS
(
    ID_ACCOUNT INT IDENTITY(1,1) NOT NULL,
    ID_EMPLOYEE INT NULL,
    ID_SCHEDULE INT NULL,
    ID_ACCOUNT_STATUS INT NULL,
    ID_ROLE INT NULL,
    LOGIN_ACCOUNT VARCHAR(50) NULL DEFAULT 'NEW_LOGIN',
    PASSWORD_ACCOUNT VARCHAR(50) NULL DEFAULT 'NEW_PASSWORD',
    PERIOD_VALIDITY_FROM DATE NULL,
    PERIOD_VALIDITY_BY DATE NULL,
    LAST_LOGIN DATETIME NULL,
    LAST_PASSWORD_CHANGE DATE NULL,

    PRIMARY KEY CLUSTERED (ID_ACCOUNT ASC),
    CONSTRAINT FK_EMPLOYEES_ACCOUNTS FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEES (ID_EMPLOYEE),
    CONSTRAINT FK_SCHEDULES_ACCOUNTS FOREIGN KEY (ID_SCHEDULE) REFERENCES SCHEDULES (ID_SCHEDULE),
    CONSTRAINT FK_ACCOUNT_STATUSES_ACCOUNTS FOREIGN KEY (ID_ACCOUNT_STATUS) REFERENCES ACCOUNT_STATUSES (ID_ACCOUNT_STATUS),
    CONSTRAINT FK_ROLES_ACCOUNTS FOREIGN KEY (ID_ROLE) REFERENCES ROLES (ID_ROLE)
);

GO 
CREATE NONCLUSTERED INDEX [IX_ACCOUNTS_ID_EMPLOYEES]
    ON [dbo].[ACCOUNTS]([ID_EMPLOYEE] ASC);

GO 
CREATE NONCLUSTERED INDEX [IX_ACCOUNTS_ID_SCHEDULE]
    ON [dbo].[ACCOUNTS]([ID_SCHEDULE] ASC);

GO
CREATE NONCLUSTERED INDEX [IX_ACCOUNTS_ID_ACCOUNT_STATUS]
    ON [dbo].[ACCOUNTS]([ID_ACCOUNT_STATUS] ASC);

GO
CREATE NONCLUSTERED INDEX [IX_ACCOUNTS_ID_ROLE]
    ON [dbo].[ACCOUNTS]([ID_ROLE] ASC);