CREATE TABLE APPOINTMENTS
(
    ID_APPOINTMENT INT IDENTITY(1, 1) NOT NULL,
    ID_POSITION INT NULL,
    PERIOD_EMPLOYMENT_FROM DATE NULL,
    PERIOD_EMPLOYMENT_BY DATE NULL,
    PERIOD_NON_PERFORMANCE_DUTIES_FROM DATE NULL,
    PERIOD_NON_PERFORMANCE_DUTIES_BY DATE NULL,

    PRIMARY KEY CLUSTERED (ID_APPOINTMENT ASC),
    CONSTRAINT FK_POSITIONS_APPOINTMENTS FOREIGN KEY (ID_POSITION) REFERENCES POSITIONS (ID_POSITION)
)

