CREATE TABLE DEPARTMENTS
(
    ID_DEPARTMENT INT IDENTITY(1, 1) NOT NULL,
    ID_ORGANIZATION INT NOT NULL,
    NAME_DEPARTMENT VARCHAR(50) NULL DEFAULT 'NEW_DEPARTMENT',

    PRIMARY KEY CLUSTERED (ID_DEPARTMENT ASC),
    CONSTRAINT FK_ORGANIZATIONS_DEPARTMENTS FOREIGN KEY (ID_ORGANIZATION) REFERENCES ORGANIZATIONS (ID_ORGANIZATION)
)

GO
CREATE NONCLUSTERED INDEX [IX_DEPARTMENTS_ID_ORGANIZATION]
    ON [dbo].[DEPARTMENTS]([ID_ORGANIZATION] ASC);