CREATE TABLE EMPLOYEE_STATUSES
(
    ID_EMPLOYEE_STATUS INT IDENTITY(1, 1) NOT NULL,
    NAME_EMPLOYEE_STATUS VARCHAR(50) NULL DEFAULT 'NEW_EMPLOYEE_STATUS',

    PRIMARY KEY CLUSTERED (ID_EMPLOYEE_STATUS ASC)
)