CREATE TABLE SCHEDULES
(
    ID_SCHEDULE INT IDENTITY(1,1) NOT NULL,
    ID_DAYS INT NULL,
    TIME_FROM TIME NULL,
    TIME_TO TIME NULL,

    PRIMARY KEY CLUSTERED (ID_SCHEDULE ASC),
    CONSTRAINT FK_DAYS_SCHEDULES FOREIGN KEY (ID_DAYS) REFERENCES WEEKDAYS (ID_WEEKDAY)
)

GO
CREATE NONCLUSTERED INDEX [IX_SCHEDULES_ID_DAYS]
    ON [dbo].[SCHEDULES]([ID_DAYS] ASC);

GO
CREATE NONCLUSTERED INDEX [IX_SCHEDULES_TIME_FROM]
    ON [dbo].[SCHEDULES]([TIME_FROM] ASC);

GO
CREATE NONCLUSTERED INDEX [IX_SCHEDULES_TIME_TO]
    ON [dbo].[SCHEDULES]([TIME_TO] ASC);